### PR TITLE
note taking logo

### PR DESCRIPTION
**Pull request by silky-modi22**
update logo for note taking

### CODE REVIEW

**Comment by silky-modi22** [comment]
What you exactly want from the logo for note taking . Please mention it
I'll try to add it

**Comment by silky-modi22** [comment]
Do I have to add the logo to the html file as well?

**Comment by Chirantanbanik** [comment]
The logo is fine but you have to add it in the html file.

**Comment by silky-modi22** [comment]
Ok now, can I add in html file?

**Comment by silky-modi22** [comment]
I added html code  of note taking logo please check and merge my pr and in
case there is some mistake please let me know.

**Comment by silky-modi22** [comment]
I updated with desired changes please merge my pull request

**Pull request merged**
